### ISSUE TITLE
Replace request with node-fetch

### ISSUE THREAD

**Issue by umireon** [Jexoio/atlassian-marketplace-aws-lambda#15]
Hello Jexoio,

We want to use this project to track our Atlassian Marketplace activities,
and I'd like to propose several pull requests to improve this project.

For the first time, I want to propose replacing the deprecated `request` package with `node-fetch` package, which is the most popular package except the `request`.

May I go to propose such pull requests?

Thanks in advance,

Kaito

**Comment by birox** [comment]
Hello, is great to hear you want to use the repo. I'm happy for you to propose improvements 100%. However, we moved the repo here: https://bitbucket.org/jexoio/atlassian-marketplace-aws-lambda/src/master/
Sorry forgot to update this one's readme. Feel to raise suggestions or PRs there.

Really appreciate it!

**Comment by umireon** [comment]
@birox Thank you, I have several other ideas to improve this project, and I will propose some issues and pull requests there!
Sorry for the late reply!

**Comment by birox** [comment]
Great, thank you @umireon! Are you on Marketplace Clarity slack? We can sync chat about changes there too

**Comment by umireon** [comment]
@birox I have just been on Marketplace Clarity slack! The name is Kaito Udagawa.
